[package]
name = "brushless_rp2350"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.10", features = ["defmt", "platform-cortex-m", "executor-thread"] }
embassy-time = { version = "0.5", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-rp = { version = "0.10", features = [
    "defmt",
    "rp235xa",
    "time-driver",
    "critical-section-impl",
    "binary-info",
] }

defmt = "1"
defmt-rtt = "1"
panic-probe = { version = "1", features = ["print-defmt"] }

cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"
critical-section = "1"
static_cell = "2"
embedded-hal-async = "1.0"

libs = { path = "../libs", default-features = false }

[profile.release]
debug = true
lto = true
opt-level = "s"

[profile.dev]
debug = 2
